### ISSUE TITLE
How do you remove a worker

### ISSUE THREAD

**Issue by Nickfost** [MultiPoolMiner/mpm-monitor#1]
my worker names have the versioning in them and i'm suspecting the only way to remove the worker that's renamed and now reporting "offline" is to remove something from sql. removing a line from SQL isn't the end of the world but a better solution would be appreciated. 

Keep up the good work

**Comment by grantemsley** [comment]
At the moment the only way is to delete them from the database.

It's definitely on my todo list to have it automatically remove ones that haven't been seen in awhile.

**Comment by Nickfost** [comment]
Nice cleanup function

**Comment by mill99** [comment]
Hi and first thank you very much for your job and for MPM :)

Could you give us a visibility for the delivry of the cleanup function ?

It's really boring to got some deads hosts in the MPM report :-S

Thank you very much in advance
